import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import TopNav from "@/components/top-nav";

const font = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Linkage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <TopNav/>
          <main className="w-[90%] mx-auto max-w-xl pb-8">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
